trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

  # Project Paths
  webAppProject: 'IW5Forms.Web.App/IW5Forms.Web.App.csproj'
  apiProject: 'IW5Forms.Api.App/IW5Forms.Api.App.csproj'
  identityProject: 'IW5Forms.IdentityProvider.App/IW5Forms.IdentityProvider.App.csproj'

  # Azure Web App Names
  webAppName: 'app-iw5-2024-team-xzatloa00-web'
  apiAppName: 'app-iw5-2024-team-xzatloa00-api'
  identityAppName: 'app-iw5-2024-team-xzatloa00-identity'

  azureSubscription: 'azure-connection'

steps:
# Install NuGet
- task: NuGetToolInstaller@1

# Restore Dependencies for the Solution
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Build and Deploy Web App
- task: VSBuild@1
  inputs:
    solution: '$(webAppProject)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)/WebApp.zip"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'                        
    WebAppName: '$(webAppName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/WebApp.zip'

# Build and Deploy API
- task: VSBuild@1
  inputs:
    solution: '$(apiProject)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)/Api.zip"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'                        
    WebAppName: '$(apiAppName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/Api.zip'