# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net8.0'
  dotNetVersion: '8.0.x'
  targetRuntime: 'win-x64'
  azureWebAppName: 'app-iw5-2024-team-xzatloa00-api'
  azureSubscription: 'azure-connection'

pool:
  vmImage: windows-latest

steps:
    - template: build-API.yml
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/IW5Forms.Api.App.csproj'
        arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --output $(build.artifactStagingDirectory)/api'
        modifyOutputPath: false

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactStagingDirectory)/api'
        ArtifactName: 'API'
        publishLocation: 'Container'
        
    - task: AzureRmWebAppDeployment@3
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '$(azureSubscription)'
        appType: 'webApp'                        
        WebAppName: '$(azureWebAppName)'
        packageForLinux: '$(build.artifactStagingDirectory)/api'
