# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net8.0'
  dotNetVersion: '8.0.x'
  targetRuntime: 'win-x64'

pool:
  vmImage: windows-latest

steps:
    - template: build-API.yml
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/IW5Forms.Api.App.csproj'
        arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --output https://app-iw5-2024-team-xzatloa00-api.azurewebsites.net/api'
        modifyOutputPath: false

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'https://app-iw5-2024-team-xzatloa00-api.azurewebsites.net/api'
        ArtifactName: 'API'
        publishLocation: 'Container'
